### ISSUE TITLE
Make the UI Prettier

### ISSUE THREAD

**Issue by agusalex** [agusalex/pdfToKindleOnline#1]
Add some styling to this plain HTML uploader

**Comment by ghost** [comment]
@agusalex Can this be plain HTML?

**Comment by agusalex** [comment]
Sure 👍  just make it pretty and check that PHP upload and convert is working 😄

**Comment by questro** [comment]
I can add some nice repsonsive css to it, too. Any name / logo to assign to it?  I can make one up, if that helps. 

(First try with pull requests, btw).

**Comment by agusalex** [comment]
Hey @questro!  it seems like @KamaZz already made a Pull Request with some styling added, anyways if you want to you can make it responsive on mobile and add some logo of your choice too! 
Be sure to checkout this branch https://github.com/agusalex/pdfToKindleOnline/tree/prettyUI

**Comment by questro** [comment]
Thanks, @agusalex , that would be great!  So I'll clone the prettyUI branch and make changes to that, correct? (I'll clone it now and get started)

**Comment by questro** [comment]
While we're at it, I think it could really use a progress bar (there's some js for that in the ui kit framework). I thought of this because I tried to test an upload and it was loading but nothing was happening after 30 seconds. 

Do you have any way to track the progress of the upload and output it with php: something along the lines of this with ajax: http://adnan-tech.com/ajax-file-upload-with-progress-bar-javascript-php/

**Comment by agusalex** [comment]
> Thanks, @agusalex , that would be great! So I'll clone the prettyUI branch and make changes to that, correct? (I'll clone it now and get started)

Thank you! Now the changes are merged (from @KamaZz pull request) so that branch is the same as master right now. To sum up, master or prettyUI is ok to use whichever you like.

Now if you want to contribute just **fork** this project make some changes in your own repo and when you are ready make a pull request in this repo using yours as source.

> While we're at it, I think it could really use a progress bar (there's some js for that in the ui kit framework). I thought of this because I tried to test an upload and it was loading but nothing was happening after 30 seconds.
> 
> Do you have any way to track the progress of the upload and output it with php: something along the lines of this with ajax: 
http://adnan-tech.com/ajax-file-upload-with-progress-bar-javascript-php/

Yes!! exactly, that would be a lot better, so the user can know how much upload is remaining. 
Also when it is converting, to have at least some kind of infinite spinning wheel that shows that work is being made.

**Comment by questro** [comment]
Hey quick newbie question: I had a look at the source files (from the prettyUI fork) yesterday and I'm wondering if I need to clone the docker image so I can work on an instance locally (hope I have that terminology right). I noticed you removed heroku and docker from the repo, so what's the easiest way to preview my changes?  I watched some videos last night and have a general idea of how docker works. But thought I'd check in first. 

How did you do it @KamaZz?

**Comment by KamaZz** [comment]
I have a docker on my local computer, I just downloaded this repository to it

**Comment by questro** [comment]
Okay, that's what I assumed I needed to do.

**Comment by agusalex** [comment]
Yes!! you should have Docker installed locally then go to the projects directory, and after making the changes do the following: `docker build -t ¨test¨ .`  
That builds you a docker image locally with your changes implemented
But we want to test it so we should run it, for that use
`docker -d -p 8080:8080 test`
Then you can head over to [http://0.0.0.0:8080](http://0.0.0.0:8080) and see your changes live!

**Comment by questro** [comment]
I had some time to install docker and built the project container locally.   
`docker build -t "test" . `
...works for me. 

The test command to run on port 8080:8080 doesn't work. 
Don't I need to run:

`docker run -publish 8080:8080 --detach --name test `

(that doesn't work either)

Thanks.

**Comment by agusalex** [comment]
Sorry its `docker run -d -p 8080:8080 test` I forgot the run command
