### ISSUE TITLE
Investigate if it makes sense to use Calibre instead of k2pdfopt

### ISSUE THREAD

**Issue by NNTin** [agusalex/pdfToKindleOnline#3]
See the CLI doc of converting via Calibre here: https://manual.calibre-ebook.com/generated/en/ebook-convert.html
Website: https://calibre-ebook.com/

It supports many more file formats and is more memory efficient. I've generated .epub, .pdf, .docx, .mobi files (from and to) that are far larger than 100 kB.

A Heroku buildpack for Calibre exists here: https://github.com/NNTin/heroku-buildpack-calibre
That buildpack is consumed by this project: https://github.com/dipu-bd/lightnovel-crawler

You can also just install Calibre on your Linux distro and play around with the `ebook-convert` command.

**Comment by agusalex** [comment]
Hi! I've tried Calibre, and use it to manage my ebooks, its an awesome tool! problem is it does not give good results when converting PDFs to Kindle (as far as I tried) especially when it contains graphics like academic papers. K2pdfopt gives amazing results, what would be awesome is for Calibre to have a k2pdfopt extension or something.
